### ISSUE TITLE
Production: Babel minify missing

### ISSUE THREAD

**Issue by schlenger** [collective-soundworks/soundworks-template-build#2]
**Command:** `npm run build:production` called from the template

**Error message:** 
> Error: Cannot find module 'babel-preset-minify'

It seems like a 'normal installation' such as here https://babeljs.io/docs/en/babel-preset-minify is not working.

**Comment by b-ma** [comment]
Yup... it seems like I have not implemented it : https://github.com/collective-soundworks/soundworks-template-build/blob/16cb9b4e57b231abbdb32e123d9145f91f0380f0/bin/soundworks-template-build.js#L6 

From what I remember terser (https://github.com/terser/terser) is a good solution, and everything is quite ready template wise https://github.com/collective-soundworks/soundworks-template/blob/master/src/server/tmpl/default.tmpl 

Let's keep that open until its fixed

**Comment by b-ma** [comment]
fixed `soundworks-template` as well 

```
// `src/server/tmpl/default.tmpl` (line 18)
(d.env.type === 'production')
```
